name: Dispatch Action When Post is Created

on:
  push:
    branches:
      - main

jobs:
  # Dispatch:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Send dispatch request
  #       run: curl -XPOST -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" -H '"Accept:application/vnd.github.everest-preview+json"' -H '"Content-Type:application/json"' https://api.github.com/repos/davyd-souza/dicebugging/actions/workflows/build.yaml/dispatches --data '{"ref":"main"}'
  Dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'davyd-souza',
              repo: 'dicebugging',
              workflow_id: 'build-vercel.yml',
              ref: 'main'
            })
